language: ruby
sudo: true
dist: trusty
rvm:
  - 2.5.1
env:
  - DB=postgresql
bundler_args: "--without production"
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bin/rails test
  - bin/rails test:system
before_script:
  - export TZ=Asia/Tokyo
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database database_test' -U postgres
  - bundle update
addons:
  chrome: stable
