language: ruby
sudo: false
dist: trusty
rvm:
  - 2.4.1
env:
  - DB=postgresql
bundler_args: "--without production"
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bin/rails test
  - bin/rails test:system
before_script:
  - export TZ=Asia/Tokyo
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database database_test' -U postgres
  - bundle update
  - mkdir travis-phantomjs
  - wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
cache: bundler
